### PR TITLE
Port to py3.8

### PR DESCRIPTION
**Pull request by vmarkovtsev**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by memory** [comment]
@rstrahan any chance we can get this and #44 reviewed/merged?

**Comment by rstrahan** [comment]
@memory @vmarkovtsev  Thank you so much for the PR, and apologies for the delayed merge.  Can you test from main branch and confirm desited behavior? (I also merged #55 )

**Comment by vmarkovtsev** [comment]
Thanks for merging @rstrahan 
We are running our production with this patch since March with great success.

**Comment by vmarkovtsev** [comment]
We will submit a few other PRs to improve the stability then.

**Comment by vmarkovtsev** [comment]
https://github.com/awslabs/pgbouncer-rr-patch/pull/56
https://github.com/awslabs/pgbouncer-rr-patch/pull/57

**Pull request merged**
